#=-=-=##=-=-=# #=-=-=#       #=-=-=#        #=-=-=#        #=-=-=##=-=-=##=-=-=#
#=-=-=##=-=-=# #=-=-=#       #=-=-=# #=-=-=#       #=-=-=# #=-=-=##=-=-=##=-=-=#
#=-=-=#        #=-=-=##=-=-=##=-=-=# #=-=-=#       #=-=-=#        #=-=-=#
#=-=-=#        #=-=-=##=-=-=##=-=-=# #=-=-=##=-=-=##=-=-=#        #=-=-=#
#=-=-=##=-=-=# #=-=-=#       #=-=-=# #=-=-=#       #=-=-=#        #=-=-=#
#=-=-=##=-=-=# #=-=-=#       #=-=-=# #=-=-=#       #=-=-=#        #=-=-=#

#
## By Screamoov
#

# Используйте NaN в настройке символа, если Вы хотите сделать что-бы все сообщения отправлялись по умолчанию в этот канал.

channels:
  local:
    symbol: "NaN"
    name: "&bЛокальный"
    format: "&9Локальный чат &8| &f%player%&8: &e&o%message%"